# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('event_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_creator_uid', models.UUIDField(default=uuid.uuid4)),
                ('action_title', models.CharField(max_length=256)),
                ('action_description', models.CharField(max_length=2048)),
                ('action_type', models.CharField(choices=[('EVENT', 'Event'), ('PHONE', 'Phone')], max_length=5)),
                ('has_cost', models.BooleanField(default=False)),
                ('more_info', models.URLField()),
                ('start_time_ms', models.IntegerField()),
                ('end_time_ms', models.IntegerField()),
                ('contact_name', models.CharField(max_length=256)),
                ('contact_phone_email', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('tags', models.CharField(blank=True, max_length=1024)),
                ('instructions', models.CharField(blank=True, max_length=2048)),
            ],
        ),
    ]
